In [25]:
import pandas as pd

df = pd.read_csv(r"C:\\Users\\acer\\OneDrive\\Documents\\Supply-Chain-Inventory-Analytics\\Data\\DataCoSupplyChainDataset.csv", encoding="latin1")

In [26]:

print(df.shape)
print(df.columns.tolist())

(180519, 53)
['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)', 'Benefit per order', 'Sales per customer', 'Delivery Status', 'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City', 'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id', 'Customer Lname', 'Customer Password', 'Customer Segment', 'Customer State', 'Customer Street', 'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market', 'Order City', 'Order Country', 'Order Customer Id', 'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id', 'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price', 'Order Item Profit Ratio', 'Order Item Quantity', 'Sales', 'Order Item Total', 'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status', 'Order Zipcode', 'Product Card Id', 'Product Category Id', 'Product Description', 'Product Image', 'Product Name', 'Product Price', 'Product Status', 'shipping date (DateOrders)', 'Shipping Mode']

In [27]:
print(df.isnull().sum())

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [28]:
print("Duplicates:", df.duplicated().sum())

Duplicates: 0

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 73.0 MB

In [30]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

In [31]:
df.describe( include ='object')

C:\Users\acer\AppData\Local\Temp\ipykernel_16184\3240871432.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe( include ='object')

,Type,Delivery Status,Category Name,Customer City,Customer Country,Customer Email,Customer Fname,Customer Lname,Customer Password,Customer Segment,...,Order City,Order Country,order date (DateOrders),Order Region,Order State,Order Status,Product Image,Product Name,shipping date (DateOrders),Shipping Mode
count,180519,180519,180519,180519,180519,180519,180519,180511,180519,180519,...,180519,180519,180519,180519,180519,180519,180519,180519,180519,180519
unique,4,4,50,563,2,1,782,1109,1,3,...,3597,164,65752,23,1089,9,118,118,63701,4
top,DEBIT,Late delivery,Cleats,Caguas,EE. UU.,XXXXXXXXX,Mary,Smith,XXXXXXXXX,Consumer,...,Santo Domingo,Estados Unidos,10/25/2016 14:39,Central America,Inglaterra,COMPLETE,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,05-09-2015 18:02,Standard Class
freq,69295,98977,24551,66770,111146,180519,65150,64104,180519,93504,...,2211,24840,5,28341,6722,59491,24515,24515,10,107752

In [32]:
for col in df.columns:
    if df[col].nunique() == 1:
        print(col)

Customer Email
Customer Password
Product Status

In [33]:
df[['Benefit per order',
    'Order Profit Per Order',
    'Sales',
    'Product Price',
    'Order Item Quantity']].describe()

,Benefit per order,Order Profit Per Order,Sales,Product Price,Order Item Quantity
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000
mean,21.974989,21.974989,203.772096,141.232550,2.127638
std,104.433526,104.433526,132.273077,139.732492,1.453451
min,-4274.979980,-4274.979980,9.990000,9.990000,1.000000
25%,7.000000,7.000000,119.980003,50.000000,1.000000
50%,31.520000,31.520000,199.919998,59.990002,1.000000
75%,64.800003,64.800003,299.950012,199.990005,3.000000
max,911.799988,911.799988,1999.989990,1999.989990,5.000000

In [34]:
cols_to_drop = [
    'Customer Email',
    'Customer Password',
    'Product Status',
    'Product Image'
]

df = df.drop(columns=cols_to_drop)

In [35]:
print(df.shape)

(180519, 49)

In [36]:
df.isnull().sum()[df.isnull().sum() > 0]

Customer Lname              8
Customer Zipcode            3
Order Zipcode          155679
Product Description    180519
dtype: int64

In [37]:
df['Customer Lname'] = df['Customer Lname'].fillna('Unknown')

df['Customer Zipcode'] = df['Customer Zipcode'].fillna(
    df['Customer Zipcode'].mode()[0]
)

In [38]:
df.isnull().sum().sum()

np.int64(336198)

In [39]:
print(df.columns.tolist())

['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)', 'Benefit per order', 'Sales per customer', 'Delivery Status', 'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City', 'Customer Country', 'Customer Fname', 'Customer Id', 'Customer Lname', 'Customer Segment', 'Customer State', 'Customer Street', 'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market', 'Order City', 'Order Country', 'Order Customer Id', 'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id', 'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price', 'Order Item Profit Ratio', 'Order Item Quantity', 'Sales', 'Order Item Total', 'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status', 'Order Zipcode', 'Product Card Id', 'Product Category Id', 'Product Description', 'Product Name', 'Product Price', 'shipping date (DateOrders)', 'Shipping Mode']

In [40]:
df = df.drop(columns=['Order Zipcode'])

In [41]:
df['Customer Lname'] = df['Customer Lname'].fillna('Unknown')

df['Customer Zipcode'] = df['Customer Zipcode'].fillna(
    df['Customer Zipcode'].mode()[0]
)

In [42]:
df = df.drop(columns=['Product Description'])

In [43]:
print(df.isnull().sum().sum())
print(df.shape)

0
(180519, 47)

In [44]:
df['order date (DateOrders)'].dtype

In [45]:
 df['shipping date (DateOrders)'].dtype

In [46]:
df['order_date_raw'] = df['order date (DateOrders)']

In [47]:
df['shipping_date_raw'] = df['shipping date (DateOrders)']

In [48]:
df['order date (DateOrders)'] = pd.to_datetime(
    df['order_date_raw'],
    errors='coerce'
)

In [49]:
df['order date (DateOrders)'].isna().sum()

np.int64(71103)

In [50]:
df[df['order_date_raw'].str.contains('-', na=False)][
    'order_date_raw'
].head(5)

37    01-12-2018 23:51
38    01-12-2018 23:30
39    01-12-2018 23:09
40    01-12-2018 22:48
41    01-12-2018 22:27
Name: order_date_raw, dtype: str

In [51]:

pd.to_datetime('01-12-2018 23:51')

Timestamp('2018-01-12 23:51:00')

In [52]:
pd.to_datetime('1/13/2018 12:27')

Timestamp('2018-01-13 12:27:00')

In [53]:
import pandas as pd
pd.__version__

'3.0.1'

In [54]:
order_test = pd.to_datetime(
    df['order_date_raw'],
    format='mixed',
    errors='coerce'
)

order_test.isna().sum()

np.int64(0)

In [55]:
df['order date (DateOrders)'].isna().sum()

np.int64(71103)

In [56]:
df['order date (DateOrders)'].head()

0   2018-01-31 22:56:00
1   2018-01-13 12:27:00
2   2018-01-13 12:06:00
3   2018-01-13 11:45:00
4   2018-01-13 11:24:00
Name: order date (DateOrders), dtype: datetime64[us]

In [57]:
df['order date (DateOrders)'].isna().sum()

np.int64(71103)

In [58]:
df.loc[37:41, ['order_date_raw', 'order date (DateOrders)']]

      order_date_raw order date (DateOrders)
37  01-12-2018 23:51                     NaT
38  01-12-2018 23:30                     NaT
39  01-12-2018 23:09                     NaT
40  01-12-2018 22:48                     NaT
41  01-12-2018 22:27                     NaT

In [59]:
order_test = pd.to_datetime(
    df['order_date_raw'],
    format='mixed',
    errors='coerce'
)

In [60]:
df['order date (DateOrders)'] = order_test

In [61]:
df['order date (DateOrders)'].isna().sum()

np.int64(0)

In [62]:
shipping_test = pd.to_datetime(
    df['shipping_date_raw'],
    format='mixed',
    errors='coerce'
)

In [63]:
shipping_test.isna().sum()

np.int64(0)

In [64]:
df['shipping date (DateOrders)'] = shipping_test

In [65]:
df['shipping date (DateOrders)'].isna().sum()

np.int64(0)

In [66]:
df[['order date (DateOrders)', 'shipping date (DateOrders)']].dtypes

order date (DateOrders)       datetime64[us]
shipping date (DateOrders)    datetime64[us]
dtype: object

In [67]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Product Price,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Product Card Id,Product Category Id,Product Price,shipping date (DateOrders)
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35920.541998,5.443460,29.719955,...,141.232550,0.120647,2.127638,203.772096,183.107609,21.974989,692.509764,31.851451,141.232550,2016-06-16 05:45:23.202433
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,9.990000,-2.750000,1.000000,9.990000,7.490000,-4274.979980,19.000000,2.000000,9.990000,2015-01-03 00:00:00
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,50.000000,0.080000,1.000000,119.980003,104.379997,7.000000,403.000000,18.000000,50.000000,2015-09-25 06:59:00
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,59.990002,0.270000,1.000000,199.919998,163.990005,31.520000,627.000000,29.000000,59.990002,2016-06-15 08:32:00
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,199.990005,0.360000,3.000000,299.950012,247.399994,64.800003,1004.000000,45.000000,199.990005,2017-03-04 21:29:00
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,1999.989990,0.500000,5.000000,1999.989990,1939.989990,911.799988,1363.000000,76.000000,1999.989990,2018-02-06 22:14:00
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.423343,1.629246,9.813646,...,139.732492,0.466796,1.453451,132.273077,120.043670,104.433526,336.446807,15.640064,139.732492,NaN

In [68]:
(df['Order Profit Per Order'] < 0).sum()

np.int64(33784)

In [69]:
(df['Order Profit Per Order'] < 0).mean() * 100

np.float64(18.714927514555253)

In [70]:
df['Order Status'].value_counts().head(10)

Order Status
COMPLETE           59491
PENDING_PAYMENT    39832
PROCESSING         21902
PENDING            20227
CLOSED             19616
ON_HOLD             9804
SUSPECTED_FRAUD     4062
CANCELED            3692
PAYMENT_REVIEW      1893
Name: count, dtype: int64

In [71]:
df['Delivery Status'].value_counts()

Delivery Status
Late delivery        98977
Advance shipping     41592
Shipping on time     32196
Shipping canceled     7754
Name: count, dtype: int64

In [72]:
(df['Delivery Status'] == 'Late delivery').mean() * 100

np.float64(54.82913155955883)

In [73]:
df['Category Name'].value_counts().head(10)

Category Name
Cleats                  24551
Men's Footwear          22246
Women's Apparel         21035
Indoor/Outdoor Games    19298
Fishing                 17325
Water Sports            15540
Camping & Hiking        13729
Cardio Equipment        12487
Shop By Sport           10984
Electronics              3156
Name: count, dtype: int64

In [74]:
df['Market'].value_counts()

Market
LATAM           51594
Europe          50252
Pacific Asia    41260
USCA            25799
Africa          11614
Name: count, dtype: int64

In [75]:
df['Customer Segment'].value_counts()

Customer Segment
Consumer       93504
Corporate      54789
Home Office    32226
Name: count, dtype: int64

In [76]:
df['Shipping Mode'].value_counts()

Shipping Mode
Standard Class    107752
Second Class       35216
First Class        27814
Same Day            9737
Name: count, dtype: int64

In [77]:
df['Late_delivery_risk'].value_counts()

Late_delivery_risk
1    98977
0    81542
Name: count, dtype: int64

In [78]:
df['Order Country'].value_counts().head(10)

Order Country
Estados Unidos    24840
Francia           13222
México            13172
Alemania           9564
Australia          8497
Brasil             7987
Reino Unido        7302
China              5758
Italia             4989
India              4783
Name: count, dtype: int64

In [79]:
df.groupby('Category Name')['Order Profit Per Order'] \
  .sum() \
  .sort_values(ascending=False) \
  .head(10)

Category Name
Fishing                 756220.767190
Cleats                  494636.919791
Camping & Hiking        427455.568106
Cardio Equipment        383011.098485
Women's Apparel         350421.029567
Water Sports            325146.960038
Indoor/Outdoor Games    318451.430554
Men's Footwear          311902.820214
Shop By Sport           129813.960315
Computers                69656.810171
Name: Order Profit Per Order, dtype: float64

In [80]:
df.groupby('Category Name')['Order Profit Per Order'] \
  .sum() \
  .sort_values() \
  .head(10)

Category Name
Strength Training     332.310091
CDs                   383.850000
As Seen on  TV!       714.429980
Books                 883.010008
Toys                  900.710000
Baby                 1525.029992
Golf Bags & Carts    1810.069992
Basketball           1845.670003
Men's Clothing       2006.039969
Video Games          2717.519997
Name: Order Profit Per Order, dtype: float64

In [81]:
df.groupby('Market')['Order Profit Per Order'] \
  .sum() \
  .sort_values(ascending=False)

Market
Europe          1.169443e+06
LATAM           1.123322e+06
Pacific Asia    8.577534e+05
USCA            5.643138e+05
Africa          2.520712e+05
Name: Order Profit Per Order, dtype: float64

In [82]:
df.groupby('Customer Segment')['Order Profit Per Order'] \
  .sum() \
  .sort_values(ascending=False)

Customer Segment
Consumer       2.073488e+06
Corporate      1.202575e+06
Home Office    6.908403e+05
Name: Order Profit Per Order, dtype: float64

In [104]:
df['order date (DateOrders)'].dt.year.value_counts().sort_index()

order date (DateOrders)
2015    62650
2016    62550
2017    53196
2018     2123
Name: count, dtype: int64

In [83]:
df['order date (DateOrders)'].dt.month.value_counts().sort_index()

order date (DateOrders)
1     17979
2     14529
3     15919
4     15435
5     15976
6     15139
7     15922
8     15912
9     15489
10    12955
11    12500
12    12764
Name: count, dtype: int64

In [84]:
df.groupby(
    df['order date (DateOrders)'].dt.month
)['Sales'].sum().sort_index()

order date (DateOrders)
1     3.459246e+06
2     2.888088e+06
3     3.125112e+06
4     3.053996e+06
5     3.185364e+06
6     3.059152e+06
7     3.188170e+06
8     3.187032e+06
9     3.164511e+06
10    3.171279e+06
11    2.703625e+06
12    2.599160e+06
Name: Sales, dtype: float64

In [85]:
df.groupby('Shipping Mode')['Sales'] \
  .sum() \
  .sort_values(ascending=False)

Shipping Mode
Standard Class    2.202239e+07
Second Class      7.145445e+06
First Class       5.674370e+06
Same Day          1.942529e+06
Name: Sales, dtype: float64

In [86]:
df.groupby('Delivery Status')['Order Profit Per Order'] \
  .mean() \
  .sort_values()

Delivery Status
Shipping canceled    20.696717
Late delivery        21.621707
Advance shipping     22.485701
Shipping on time     22.709146
Name: Order Profit Per Order, dtype: float64

In [87]:
pd.crosstab(
    df['Market'],
    df['Delivery Status'],
    normalize='index'
) * 100

Delivery Status,Advance shipping,Late delivery,Shipping canceled,Shipping on time
Market,,,,
Africa,22.774238,54.589289,3.960737,18.675736
Europe,23.091618,55.207753,4.302316,17.398313
LATAM,23.334109,54.355158,4.428810,17.881924
Pacific Asia,22.959283,55.046049,4.059622,17.935046
USCA,22.601651,54.800574,4.542812,18.054963

In [88]:
pd.crosstab(
    df['Shipping Mode'],
    df['Delivery Status'],
    normalize='index'
) * 100

Delivery Status,Advance shipping,Late delivery,Shipping canceled,Shipping on time
Shipping Mode,,,,
First Class,0.000000,95.322499,4.677501,0.000000
Same Day,0.000000,45.743042,4.559926,49.697032
Second Class,0.000000,76.632781,4.003862,19.363358
Standard Class,38.599748,38.071683,4.268134,19.060435

In [89]:
df.groupby('Shipping Mode')['Order Profit Per Order'] \
  .mean() \
  .sort_values(ascending=False)

Shipping Mode
First Class       23.122238
Standard Class    21.999169
Second Class      21.305889
Same Day          20.850203
Name: Order Profit Per Order, dtype: float64

In [90]:
df[['Sales', 'Order Profit Per Order']].corr()

                           Sales  Order Profit Per Order
Sales                   1.000000                0.131816
Order Profit Per Order  0.131816                1.000000

In [91]:
df.groupby('Category Name')['Sales'] \
  .sum() \
  .sort_values(ascending=False) \
  .head(10)

Category Name
Fishing                 6.929654e+06
Cleats                  4.431943e+06
Camping & Hiking        4.118426e+06
Cardio Equipment        3.694843e+06
Women's Apparel         3.147800e+06
Water Sports            3.113845e+06
Men's Footwear          2.891758e+06
Indoor/Outdoor Games    2.888994e+06
Shop By Sport           1.309522e+06
Computers               6.630000e+05
Name: Sales, dtype: float64

In [92]:
df.groupby('Category Name')[['Sales', 'Order Profit Per Order']].sum() \
  .sort_values('Sales', ascending=False)

                             Sales  Order Profit Per Order
Category Name
Fishing               6.929654e+06           756220.767190
Cleats                4.431943e+06           494636.919791
Camping & Hiking      4.118426e+06           427455.568106
Cardio Equipment      3.694843e+06           383011.098485
Women's Apparel       3.147800e+06           350421.029567
Water Sports          3.113845e+06           325146.960038
Men's Footwear        2.891758e+06           311902.820214
Indoor/Outdoor Games  2.888994e+06           318451.430554
Shop By Sport         1.309522e+06           129813.960315
Computers             6.630000e+05            69656.810171
Electronics           3.710346e+05            40891.379918
Cameras               2.676077e+05            30289.799946
Garden                2.577687e+05            33443.010106
Children's Clothing   2.328292e+05            27178.099597
Crafts                2.233563e+05            25531.170060
Girls' Apparel        1.517062e+05            17288.569973
Women's Clothing      1.402830e+05            19102.849930
Accessories           1.336715e+05            16643.520074
Sporting Goods        1.170068e+05            12518.610119
Golf Gloves           1.166954e+05            12975.490078
Music                 1.131221e+05            14436.319923
Consumer Electronics  1.089913e+05            13223.399926
Golf Shoes            1.079980e+05            12406.070143
Health and Beauty     1.060805e+05             9493.629974
Kids' Golf Clubs      9.879758e+04             9045.839896
Baseball & Softball   9.405715e+04            12762.130067
Boxing & MMA          8.520541e+04             8641.370006
DVDs                  7.939554e+04             6655.430088
Golf Balls            7.709816e+04             8342.670024
Trade-In              6.872178e+04             7915.369985
Hunting & Shooting    5.684842e+04             5979.999945
Strength Training     5.489553e+04              332.310091
Hockey                4.836073e+04             5397.430013
Men's Golf Clubs      4.703580e+04             5517.989977
Tennis & Racquet      4.458509e+04             5747.979996
Women's Golf Clubs    4.454597e+04             5028.639929
Men's Clothing        4.385680e+04             2006.039969
Pet Supplies          4.152480e+04             3589.259959
Lacrosse              3.946479e+04             4364.289984
Fitness Accessories   3.560144e+04             5258.390016
Golf Apparel          3.496975e+04             3496.309983
Video Games           3.331050e+04             2717.519997
Basketball            2.709933e+04             1845.670003
Soccer                2.647705e+04             3901.949953
As Seen on  TV!       2.059794e+04              714.429980
Books                 1.258740e+04              883.010008
Baby                  1.222956e+04             1525.029992
Golf Bags & Carts     1.036939e+04             1810.069992
Toys                  6.104660e+03              900.710000
CDs                   3.059590e+03              383.850000

In [93]:
df.to_csv('final_supply_chain_eda_ready.csv', index=False)

In [94]:
df.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Fname', 'Customer Id', 'Customer Lname',
       'Customer Segment', 'Customer State', 'Customer Street',
       'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude',
       'Longitude', 'Market', 'Order City', 'Order Country',
       'Order Customer Id', 'order date (DateOrders)', 'Order Id',
       'Order Item Cardprod Id', 'Order Item Discount',
       'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price',
       'Order Item Profit Ratio', 'Order Item Quantity', 'Sales',
       'Order Item Total', 'Order Profit Per Order', 'Order Region',
       'Order State', 'Order Status', 'Product Card Id', 'Product Category Id',
       'Product Name', 'Product Price', 'shipping date (DateOrders)',
       'Shipping Mode', 'order_date_raw', 'shipping_date_raw'],
      dtype='str')

In [96]:
df.drop(columns=['order_date_raw', 'shipping_date_raw']).to_csv(
    'supply_chain_analytics_dataset.csv',
    index=False
)